### ISSUE TITLE
Github link on map

### ISSUE THREAD

**Issue by Lili-Gigi** [RemDelaporteMathurin/fusion-world#16]

**Comment by RemDelaporteMathurin** [comment]
It would be great to have a github logo or something on the map redirecting to the github repo. This could encourage contributions to the map. 

Maybe @BilelJegham has an idea?

**Comment by RemDelaporteMathurin** [comment]
![image](https://user-images.githubusercontent.com/40028739/126602471-c1144cdd-c715-4241-977d-76941efb6ae4.png)
Would something like this do?
