### ISSUE TITLE
Pegasus repeated at Wisconsin

### ISSUE THREAD

**Issue by xavinavarro1** [RemDelaporteMathurin/fusion-world#40]
Unsure why, but after committing, I'm unable to push the changes I've made (some issues with 2-Factor authentication). Figured, to notify at least.

**Comment by RemDelaporteMathurin** [comment]
@xavinavarro1 thank you so much for willing to contribute!

You cannot push directly to this repo. Instead, create a fork (see the fork button in the top right?), then this will create a copy of this repo where you can push.

Once you comitted your changes, open a Pull Request (PR) and we will review your changes and add them to this repo.

More here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks
And here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests


What did you want to change/add in Fusion World? Is there someting wrong with Pegasus?

**Comment by RemDelaporteMathurin** [comment]
Oh I see, the device appears twice on the map.
The entry that hasn't the tokamak properties can be removed from tokamaks.json then.
